# Generated by Django 5.1 on 2024-09-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_preference', models.CharField(max_length=100)),
                ('pace_preference', models.CharField(max_length=100)),
                ('character_preference', models.CharField(max_length=100)),
                ('ending_preference', models.CharField(max_length=100)),
                ('setting_preference', models.CharField(max_length=100)),
                ('length_preference', models.CharField(max_length=100)),
                ('emotional_tone_preference', models.CharField(max_length=100)),
                ('romance_preference', models.CharField(max_length=100)),
                ('narrative_style_preference', models.CharField(max_length=100)),
                ('world_building_importance', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
