# Generated by Django 5.1 on 2024-09-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_movies', '0003_book_delete_userquizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.TextField(blank=True),
        ),
    ]
