# Generated by Django 5.1 on 2024-09-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_movies', '0005_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reviews',
        ),
        migrations.AddField(
            model_name='book',
            name='character',
            field=models.CharField(default='hero', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='emotional_tone',
            field=models.CharField(default='lighthearted', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='ending',
            field=models.CharField(default='open', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='length',
            field=models.CharField(default='medium', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='narrative_style',
            field=models.CharField(default='third_person', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='pace',
            field=models.CharField(default='medium', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='romance',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='world_building_importance',
            field=models.CharField(default='somewhat', max_length=100),
        ),
    ]
